Test file creation

diff --git a/.github/workflows/test-pr.yml b/.github/workflows/test-pr.yml
--- a/.github/workflows/test-pr.yml
+++ b/.github/workflows/test-pr.yml
@@ -11,13 +11,13 @@ jobs:
     steps:
       - name: Test
         run: echo "🎉 The test PR Action."
-      - name: 🛎 Checkout
-        uses: actions/checkout@v2
-      - name: Fail
-        run: exit 1
-      - name: Always do something
-        uses: actions/upload-artifact@v3
-        if: always()
-        with:
-          name: TestUpload
-          path: Test
+      # - name: 🛎 Checkout
+      #   uses: actions/checkout@v2
+      # - name: Fail
+      #   run: exit 1
+      # - name: Always do something
+      #   uses: actions/upload-artifact@v3
+      #   if: always()
+      #   with:
+      #     name: TestUpload
+      #     path: Test
